<?php

namespace Dhii\WpProvision\Api;

use Dhii\WpProvision\Output\OutputInterface;
use Symfony\Component\Process\Process;

/**
 * Something that can represent a result of running a WP CLI command.
 *
 * @since [*next-version*]
 */
interface CommandResultInterface extends StatusAwareInterface
{
    /**
     * Output generated by the command.
     *
     * @since [*next-version*]
     *
     * @return string|OutputInterface The output.
     */
    public function getOutput();

    /**
     * Determine of the command, of which this is a result, was a success.
     *
     * @since [*next-version*]
     *
     * @return bool True if this instance represents a successful result;
     *              false otherwise.
     */
    public function isSuccess();

    /**
     * Retrieve instance of the process, which was created by the command.
     *
     * @since [*next-version*]
     *
     * @return Process The text of the command.
     */
    public function getProcess();

    /**
     * Retrieves any structured data that may have been generated by the command.
     *
     * @since [*next-version*]
     *
     * @return null|mixed The data, if any.
     */
    public function getData();

    /**
     * Retrieves the text representation of the result.
     *
     * @since [*next-version*]
     *
     * @return string The text representation of this instance.
     */
    public function __toString();
}
